// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
import 'zokrates/code/square/verifier.sol';

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps

    
// Test verification with incorrect proof
